### ISSUE TITLE
Imitating bulk delete

### ISSUE THREAD

**Issue by adriandmitroca** [drewminns/slackdeletron#36]
Since bulk delete is not an option anymore due to Slack's API changes and manual deletions is a true pain, I think it would be great to bring back Bulk Delete button that just queues all files and deletes them one by one with some small delay.

Optionally to flash some kind of error about exceeding API limit.

What do you think? Behind the scenes it shouldn't much differ from manual deleting.

**Comment by drewminns** [comment]
Absolutely! I've thought about a process to do it, however it would require deeper server sessions in the case that a user couldn't keep their browser open.

I think it's a great opportunity for someone to add this feature as it's pretty beefy :)

**Comment by adriandmitroca** [comment]
Sounds good to me (serverless idea of course), I suppose I could tackle it on next week, what would you say?

**Comment by gardner** [comment]
I just open the developer console in Chrome and paste this in:

```
    function delFile() {
        var list = document.getElementsByTagName('h2')
        for (var i = 0; i < list.length; i++) {
            if (list[i] && list[i].innerText && list[i].innerText == 'Zap! Deleted!') {
                document.getElementsByClassName('Button Button__Large')[0].click()
            }
        }

        var button = document.getElementsByClassName('File__Button')[0]
        if (button) {
            //console.log(button)
            button.click()
        }
        var interval = 1000 + (Math.random() * 2000)
        setTimeout(delFile, interval)
    }
    setTimeout(delFile, 3000)
```

**Comment by boisei0** [comment]
Here's a [hacky tampermonkey script](https://gist.github.com/boisei0/bf7e5f071bf2042f8300b238a92d4f97) I put together for my fellow workspace members because slackdeletron is needed on our free workspace _quite_ often. 😛 It's based on the previous comment.
The check on the button has an else added because it's pretty unforgiving and will keep deleting on new searches. Might not be wanted behaviour for everyone, so it will need an extra click on the nuke button :)
